INSERT INTO concours_schools (code, name, level, description, subjects, is_active) VALUES
('CFEE', 'Certificat de Fin d''Etudes Elementaires', 'cm2', 'Examen de fin de cycle elementaire obligatoire pour tous les eleves du Senegal', ARRAY['Francais','Mathematiques','Sciences','Histoire-Geographie','Education Civique'], true),
('BFEM', 'Brevet de Fin d''Etudes Moyennes', 'bfem', 'Examen national de fin de cycle moyen - passage vers le lycee', ARRAY['Francais','Mathematiques','Physique-Chimie','SVT','Histoire-Geographie','Anglais','Education Civique'], true),
('BAC-S1', 'Baccalaureat Serie S1', 'bac', 'Baccalaureat scientifique - Mathematiques et Sciences de la Nature', ARRAY['Mathematiques','Physique-Chimie','SVT','Francais','Philosophie','Anglais'], true),
('BAC-S2', 'Baccalaureat Serie S2', 'bac', 'Baccalaureat scientifique - Mathematiques et Sciences Physiques', ARRAY['Mathematiques','Physique-Chimie','Francais','Philosophie','Anglais'], true),
('BAC-S3', 'Baccalaureat Serie S3', 'bac', 'Baccalaureat scientifique - Sciences Experimentales', ARRAY['Physique-Chimie','SVT','Mathematiques','Francais','Philosophie'], true),
('BAC-L1', 'Baccalaureat Serie L1', 'bac', 'Baccalaureat litteraire - Lettres et Sciences Humaines', ARRAY['Francais','Philosophie','Histoire-Geographie','Anglais','Mathematiques'], true),
('BAC-L2', 'Baccalaureat Serie L2', 'bac', 'Baccalaureat litteraire - Langues Vivantes', ARRAY['Francais','Philosophie','Anglais','Espagnol','Allemand','Arabe'], true),
('BAC-G', 'Baccalaureat Serie G', 'bac', 'Baccalaureat technique de gestion', ARRAY['Comptabilite','Economie','Mathematiques','Francais','Droit'], true),
('ENA', 'Ecole Nationale d''Administration', 'licence', 'Concours d''entree a l''ENA - Formation des cadres de l''Etat', ARRAY['Culture Generale','Droit Constitutionnel','Economie','Francais','Dissertation'], true),
('ENAM', 'Ecole Nationale d''Administration et de Magistrature', 'licence', 'Formation des magistrats et administrateurs civils', ARRAY['Droit Civil','Droit Penal','Droit Constitutionnel','Culture Generale','Dissertation'], true),
('ESP', 'Ecole Superieure Polytechnique', 'licence', 'Concours d''entree a l''ESP de Dakar - Ingenieurs et techniciens', ARRAY['Mathematiques','Physique','Chimie','Informatique','Anglais'], true),
('FASTEF', 'Faculte des Sciences et Technologies de l''Education', 'licence', 'Formation des enseignants du Senegal - FASTEF/UCAD', ARRAY['Pedagogie','Didactique','Discipline principale','Culture Generale','Francais'], true),
('DOUANES', 'Concours des Douanes', 'licence', 'Concours d''entree dans l''administration des Douanes senegalaises', ARRAY['Culture Generale','Mathematiques','Francais','Droit','Economie'], true),
('POLICE', 'Concours de Police', 'licence', 'Concours de recrutement de la Police nationale du Senegal', ARRAY['Culture Generale','Droit','Francais','Mathematiques','Sport'], true),
('GENDARMERIE', 'Concours de Gendarmerie', 'licence', 'Concours de recrutement de la Gendarmerie nationale', ARRAY['Culture Generale','Droit','Francais','Mathematiques','Sport'], true),
('EAUX-FORETS', 'Concours des Eaux et Forets', 'licence', 'Concours des agents des Eaux, Forets et Chasses', ARRAY['SVT','Geographie','Culture Generale','Francais','Mathematiques'], true),
('CESTI', 'Centre d''Etudes des Sciences et Techniques de l''Information', 'licence', 'Ecole de journalisme de l''UCAD - Concours d''entree', ARRAY['Culture Generale','Francais','Anglais','Dissertation','Actualites'], true),
('FMPO', 'Faculte de Medecine, Pharmacie et Odontologie', 'licence', 'Concours d''entree en medecine, pharmacie et dentaire a l''UCAD', ARRAY['Biologie','Chimie','Physique','Mathematiques'], true),
('PRYTANEE', 'Prytanee Militaire de Saint-Louis', 'bfem', 'Concours d''entree au Prytanee Militaire Charles Ntchorere', ARRAY['Mathematiques','Francais','Sciences','Dictee','Culture Generale'], true),
('ENSEPT', 'Ecole Normale Superieure d''Enseignement Technique et Professionnel', 'licence', 'Formation des professeurs d''enseignement technique', ARRAY['Discipline technique','Mathematiques','Francais','Pedagogie'], true),
('ENTSS', 'Ecole Nationale des Travailleurs Sociaux Specialises', 'licence', 'Formation en travail social et action communautaire', ARRAY['Culture Generale','Francais','Sciences Sociales','Psychologie'], true),
('ENSA', 'Ecole Nationale Superieure d''Agriculture', 'licence', 'Concours d''entree en agronomie - Thies', ARRAY['Biologie','Chimie','Mathematiques','Physique','Francais'], true),
('BTS', 'Brevet de Technicien Superieur', 'licence', 'Examen national BTS - Toutes filieres', ARRAY['Discipline principale','Mathematiques','Francais','Anglais','Economie'], true)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  subjects = EXCLUDED.subjects,
  is_active = EXCLUDED.is_active;
